In [1]:
import tensorflow as tf

In [2]:
print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.9.1


In [5]:
# Create a tensor constant
A = tf.constant([[1, 2], 
                 [3, 4]])

In [6]:
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [7]:
# Create a tensor variable
V = tf.Variable([[5, 6],
                 [7, 8]])

In [8]:
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [11]:
AV = tf.concat(values=[A, V], axis=1)
AV

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]])>

In [12]:
AV = tf.concat(values=[A, V], axis=0)
AV

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [20]:
zero_tensor = tf.zeros(shape=[4, 5], dtype=tf.int32)
zero_tensor

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [21]:
ones_tensor = tf.ones(shape=[4, 5], dtype=tf.int32)
ones_tensor

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [31]:
reshaped_tensor = tf.reshape(tensor=ones_tensor, shape=[5, 4])
reshaped_tensor

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [43]:
reshaped_tensor = tf.reshape(tensor=ones_tensor, shape=[2, 2, 5])
reshaped_tensor

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])>

In [39]:
random_tensor = tf.random.uniform(shape=[4, 4])
random_tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.9760771 , 0.34800458, 0.8906753 , 0.47370362],
       [0.8987992 , 0.4770651 , 0.8006958 , 0.83388436],
       [0.92414594, 0.72930646, 0.33974397, 0.23419273],
       [0.5848918 , 0.5464306 , 0.5309191 , 0.80116117]], dtype=float32)>

In [40]:
random_tensor_int = tf.cast(random_tensor, dtype=tf.int32)
random_tensor_int

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [44]:
trans = tf.transpose(reshaped_tensor)
trans

<tf.Tensor: shape=(5, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])>

In [48]:
# matrix multiplication
mul = tf.matmul(A, V)
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [49]:
# element wise multiplication
bit_mul = tf.multiply(A, V)
bit_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [50]:
rows, cols = bit_mul.shape
print("Rows:", rows)
print("Columns:", cols)

Rows: 2
Columns: 2


In [52]:
identity_tensor = tf.eye(num_rows=4, num_columns=3, dtype=tf.int32)
identity_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])>

In [3]:
graph = tf.compat.v1.get_default_graph()

In [5]:
graph.get_operations()

[]

In [9]:
a = tf.constant(10,name="a")